name: patroleum_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  video_player_platform_interface: '>=6.1.0 <7.0.0'
  logging: ^1.2.0
  flutter_bloc: ^8.1.3
  oauth2: ^2.0.2
  url_launcher: ^6.2.2
  star_menu: ^3.1.4
  video_player: ^2.8.1
  pulsator: ^1.0.0
  patroleum_lib:
    path: ../PatroleumLib-main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  pigeon: ^9.2.5
topics:
  - video
  - video-player
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin