name: video_player_android
description: Android implementation of the video_player plugin.
version: 2.4.10
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ">=6.1.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.5

topics:
  - video
  - video-player
