name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
version: 2.7.2
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_android:
    path:
      ../video_player_android

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
